engines:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
          mass_threshold: 90

  csslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO

ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
exclude_paths:
  - "backend/public"
  - "frontend/public"
  - "frontend/node_modules"
  - "frontend/__tests__"
  - "frontend/webpack.config.js"
  - "frontend/assets/styles/carousel_internal_slide.css"
